# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "dropshipping"
client_id = "517970af256910337cded08dd7201f46"
application_url = "https://entities-vary-adapters-encouraging.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://entities-vary-adapters-encouraging.trycloudflare.com/auth/callback",
  "https://entities-vary-adapters-encouraging.trycloudflare.com/auth/shopify/callback",
  "https://entities-vary-adapters-encouraging.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sh-clint.myshopify.com"
